; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dfrobot_beetle_esp32c3]
platform = espressif32
board = dfrobot_beetle_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps = 
	; makuna/NeoPixelBus@^2.8.3
	; adafruit/Adafruit NeoPixel@^1.12.4
	fastled/FastLED@^3.9.14
monitor_rts = 0
monitor_dtr = 1
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1



[platformio]
default_envs = upesy_wroom

[env:upesy_wroom]
platform = https://github.com/pioarduino/platform-espressif32/archive/refs/tags/54.03.20-rc2.zip
board = upesy_wroom
monitor_speed = 112500
framework = arduino
lib_deps = fastled/FastLED@^3.9.14
